In [19]:
#数据API

import tensorflow as tf
x = tf.range(10)
dataset = tf.data.Dataset.from_tensor_slices(x)
# dataset = tf.data.Dataset.range(10)
# for item in dataset:
#     print(item)
    
dataset = dataset.repeat(3).batch(7)   #重复dataset元素3遍
# for item in dataset:
#     print(item)
    
    
dataset = tf.data.Dataset.from_tensor_slices(x)
dataset = dataset.map(lambda x:x*2)   #所有数据扩大两倍
# for item in dataset:
#     print(item)

dataset = dataset.filter(lambda x:x<10)   #过滤数据集
for item in dataset:
    print(item)
    

for item in dataset.take(2):    #打印前两个数据
    print(item)
    
    

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [1]:
#乱序数据 
import tensorflow as tf
dataset = tf.data.Dataset.range(10).repeat(3)
dataset = dataset.shuffle(buffer_size=5,seed=42).batch(7)
for item in dataset:
    print(item)

tf.Tensor([0 2 3 6 7 9 4], shape=(7,), dtype=int64)
tf.Tensor([5 0 1 1 8 6 5], shape=(7,), dtype=int64)
tf.Tensor([4 8 7 1 2 3 0], shape=(7,), dtype=int64)
tf.Tensor([5 4 2 7 8 9 9], shape=(7,), dtype=int64)
tf.Tensor([3 6], shape=(2,), dtype=int64)


In [21]:
file = r'E:\电脑数据\AI地学\地学数据.txt'
data = tf.data.TextLineDataset(file)
a = []
for i in data.take(5):
    a.append(i.numpy())
    print(i.numpy())
# print(a)



b'0.4'
b'18.6'
b'38.9'
b'57.2'
b'26.7'


In [24]:
#独热编码

train_lable = tf.constant(['1','2','3','2','3','1','1'])
train_lable_onehot=tf.keras.utils.to_categorical(train_lable)
print(train_lable_onehot)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]]


In [1]:
#将颜色这一列进行独热编码
import pandas as pd
from pandas import DataFrame
data = {'color':['green','red','blue'],'size':['M','L','XL'],'price':['10.1','13.5','15.3'],'classlabel':['class1','class2','class1']}
df = DataFrame(data)
print(df)

from sklearn.preprocessing import LabelEncoder
class_le = LabelEncoder()
y = class_le.fit_transform(df['classlabel'].values)
print(y)

b = pd.get_dummies(df['color'])
# print(b)
df = df.drop('color',axis=1)
data = pd.concat([b,df],axis=1)
data

   color size price classlabel
0  green    M  10.1     class1
1    red    L  13.5     class2
2   blue   XL  15.3     class1
[0 1 0]
   blue  green  red
0     0      1    0
1     0      0    1
2     1      0    0


blue  green  red size price classlabel
0     0      1    0    M  10.1     class1
1     0      0    1    L  13.5     class2
2     1      0    0   XL  15.3     class1

In [ ]:
#表征学习    p328
import tensorflow as tf
from tensorflow import keras
regular_inputs = keras.layers.Input(shape=[8])
categories = keras.layers.Input(shape=[],dtype=tf.string)
cat_indices = kersa.layers.Lambda(lambda cats: table.lookup(cats))(categories)
cat_embed = keras.layers.Embedding(input_dim=6,output_dim=2)(cat_indices)
encoded_inputs = keras.layers.concatenate([regular_inputs,cat_embed])
outputs = keras.layers.Dense(1)(encoding_inputs)
model = keras.models.Model(inputs=[regular_inputs,categories],outputs=[outputs])
