In [53]:
import numpy as np
from sklearn.model_selection import KFold
import pandas as pd

X = np.random.randint(1,100,20).reshape((10,2))
y = np.random.randint(1,100,10).reshape((10,1))

for X_train,X_test in kf.split(X=X,y=y):
    print(X_train,X_test)


[2 3 4 5 6 7 8 9] [0 1]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 6 7] [8 9]


In [ ]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(model,x,y,scoring='accuracy',cv=10)
